import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/common/header";
import { ThemeProvider } from "@/components/theme/theme-provider";
import Footer from "@/components/common/footer";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Marcos Camara's blog and portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${inter.className} scroll-smooth`}
    >
      <body>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <main className="p-6 pt-3 md:pt-6 min-h-screen">
            <Header />

            {children}

            <Footer />
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
